relativeURLs = true
title = "Marguerite Obolensky"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    logo = "index_picture.jpg"
    # shortbio = "Lecturer, University College London"
    
