---
title: "Research"
favicon: images/default-favicon.ico
---
<script>
function hide_buttons(abstract) {
    var x = document.getElementById(abstract);
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>

### Working papers 

**Homeward Bound: How Migrants Seek Out Familiar Climates**  
with Marco Tabellini and Charles Taylor (Submitted) 

<div class="button-bar">
<a href="content/working_papers/homeward_bound.pdf" class="button_that_looks_like_link">latest version </a>
//
<a href="https://www.nber.org/papers/w32035?utm_campaign=ntwh&utm_medium=email&utm_source=ntwg18" class="button_that_looks_like_link">nber </a>
//
<a href="https://cepr.org/voxeu/columns/homeward-bound-how-migrants-seek-out-familiar-climates" class="button_that_looks_like_link">vox</a>
//
<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('abstract_homeward_bound')">abstract</button>
</div>

<div id="abstract_homeward_bound" style="display: none;">
  This paper introduces the concept of "climate matching" as a driver of migration. Using historical censuses and administrative data, we document several novel findings. First, we show that climate strongly predicts the spatial distribution of international and domestic migrants in the US, both historically (1850-1940) and more recently (2011-2019), whereby movers select destinations with climates similar to those in their origin. Second, we analyze historical flows of German, Norwegian, and domestic migrants in the US and find that climate sorting also holds within countries. Third, we exploit variation in the long-run change in average US climate from 1900 to 2019 and find evidence of climate matching over time, with migration increasing between locations whose climate converged. Our results hold across time, geography, and migrant groups and are not driven by the persistence of ethnic networks or other confounders. We provide evidence for two complementary mechanisms: climate-specific human capital and climate as amenity. We then back out the marginal value of climate by: $i)$ exploiting the 1862 Homestead Act, a public policy that changed relative land prices; and, $ii)$ estimating the effect of climate mismatch on life expectancy. We conclude by projecting how climate change can reshape the geography of US internal migration throughout the 21st century.
</div>


### Works in Progress

**Resilient Agriculture: a Dynamic Land Use Approach to Insurance Design in a Changing
Climate** 

<div class="button-bar">
<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('JMP')">abstract</button>
</div>

<div id="JMP" style="display: none;">
Weather variability represents a large threat to agricultural yields. In response, crop insurance has emerged as a crucial policy tool in the United States, offering premium subsidies to farmers in counties with historical crop cultivation. This reduces the program's exposure to climate-related risks by not insuring farmers in regions where sufficient data are lacking. However, it also contributes to locking farmers in current cropland areas. With climate change shifting suitable growing areas, farmers will be faced with the challenge of spatially reallocating agricultural production. I combine parcel-level land use data and county-level insurance data obtained from the Risk Management Agency with a dynamic model of crop choice and insurance take up to study the trade-off between managing actuarial costs and adapting crop insurance to facilitate gradual crop migration.
</div>

<br> 

**Local Crop Species Diversity and Pest Diffusion: Evidence from the US Census of Agriculture** <br/>  with Tristan du Puy

<div class="button-bar">
<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('crop_diversity_pests')">abstract</button>
</div>

<div id="crop_diversity_pests" style="display: none;">
We provide evidence of the role of local agricultural crop diversity, measured by local crop richness and evenness, in hampering the diffusion of pests. First, we build consistent county-level diversity measures using a new machine-learning based method to link the US Agricultural Census of Agriculture between 1880-2007. Second, we show large declines in local crop diversity over the second half of 20th century, consistent with previous findings. Finally, we examine the impact of crop diversity on the spread of two significant pest outbreaks in US agricultural systems—the boll weevil (1890-1930) and the imported fire ant (1940-1997). We address reverse causality concerns by instrumenting local crop diversity with the expected (pre-planting) spread in crop revenues. We find that increases in crop diversity prevented the diffusion of these two pests.
</div>

<br> 

**News Media Concentration and Content Diversity** <br/> with Pierre Bodéré and Nicolas Longuet Marx

<div class="button-bar">
<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('abstract_media')">abstract</button>
</div>

<div id="abstract_media" style="display: none;">
The rise in political polarization over the recent years has fostered scrutiny of the structure of the news industry’ s influence on political outcomes. How should policymakers regulate news producers when they value news diversity and large publishers shape the ideological landscape? We develop an empirical model of competition for readership and advertisers between news producers. We recover the topic content and ideological positions of 200 major U.S. daily newspapers using recent advances in Natural Language Processing on millions of published articles. We find that over the period 2007-2017, the median newspaper in our sample got closer to the ideology of the Democratic party. Second, we embed these topics and ideal points in a demand model for differentiated products with heterogeneous readers. Our model shows that rich readers lean democrat and consume more news about social and political questions while the elderly are more conservative and care more about local news. Using the estimated demand model and data on advertising contracts and readership, we can recover the cost of producing each type of content. Given this model of news supply, we intend to use our framework to provide recommendations on antitrust rules weighing both consumer welfare and ideological diversity.
</div>

<br> 

### Pre-Doctoral Work

**Wading Out the Storm: The Role of Poverty in Exposure, Vulnerability and Resilience to Floods in Dar Es Salaam**  <br/> with Alvina Erman, Mersedeh Tariverdi, Xiaomeng Chen, Rose Vincent, Silvia Malgioglio, Jun Rentschler, Stéphane Hallegatte, Nobuo Yoshida 

<div class="button-bar">
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3436477" class="button_that_looks_like_link">paper</a>
//
<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('wading_out')">abstract</button>
</div>

<div id="wading_out" style="display: none;">
Dar es Salaam is frequently affected by severe flooding causing destruction and impeding daily life of its 4.5 million inhabitants. The focus of this paper is on the role of poverty in the impact of floods on households, focusing on both direct (damage to or loss of assets or property) and indirect (losses involving health, infrastructure, labor, and education) impacts using household survey data. Poorer households are more likely to be affected by floods; directly affected households are more likely female-headed and have more insecure tenure arrangements; and indirectly affected households tend to have access to poorer quality infrastructure. Focusing on the floods of April 2018, affected households suffered losses of 23 percent of annual income on average. Surprisingly, poorer households are not over-represented among the households that lost the most - even in relation to their income, possibly because 77 percent of total losses were due to asset losses, with richer households having more valuable assets. Although indirect losses were relatively small, they had significant well-being effects for the affected households. It is estimated that households? losses due to the April 2018 flood reached more than US$100 million, representing between 2-4 percent of the gross domestic product of Dar es Salaam. Furthermore, poorer households were less likely to recover from flood exposure. The report finds that access to finance play an important role in recovery for households.
</div>

**Candle in the Wind? Energy System Resilience to Natural Shocks**<br/> with Jun Rentschler and Martin Kornejew 

<div class="button-bar">
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3430507" class="button_that_looks_like_link">paper</a>
//
<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('candle_in_wind')">abstract</button>
</div>

<div id="candle_in_wind" style="display: none;">
This study finds that natural shocks -- storms in particular -- are a significant and often leading cause for power supply disruptions. This finding is based on 20 years of high frequency (i.e. daily) data on power outages and climate variables in 28 countries -- Bangladesh, the United States and 26 European countries. More specifically: (1) Natural shocks are the most important cause of power outages in developed economies. On average, they account for more than 50 of annual outage duration in both the US and Europe. In contrast, natural shocks are responsible for a small share of outages in Bangladesh, where disruptions occur on a daily basis for a variety of reasons. (2) Outages due to natural shocks are found to last significantly longer than those due to non-natural shocks in -- e.g. more than 4.5 times in Europe. Reasons include the challenge of locating wide-spread damages, and the sustained duration of storms. (3) Several factors can reinforce the adverse effect of natural shocks on power supply. In the US, forest cover is shown to significantly increase the risk of power outages when storms occur. (4) There are significant differences in network fragility. For instance, wind speeds above 35 km/h are found to be 12 times more likely to cause an outage in Bangladesh than in the US. This difference may be explained by a range of factors, including investments in infrastructure resilience and maintenance.
</div>

**Underutilized Potential: The Business Costs of Unreliable Infrastructure in Developing Countries** <br/>
with Jun Rentschler, Martin Kornejew, Stéphane Hallegatte and Johannes Braese 

<div class="button-bar">
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3430509" class="button_that_looks_like_link">paper</a>
//
<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('underutilized_potential')">abstract</button>
</div>
<div id="underutilized_potential" style="display: none;">
This study constructs a microdata set of about 143,000 firms to estimate the monetary costs of infrastructure disruptions in 137 low- and middle-income countries, representing 78 percent of the world population and 80 percent of the GDP of low- and -middle-income countries. Specifically, this study assesses the impact of transport, electricity, and water disruptions on the capacity utilization rates of firms. The estimates suggest that utilization losses amount to \$151 billion a year -- of which \$107 billion are due to transport disruptions, \$38 billion due to blackouts, and \$6 billion due to dryouts. Moreover, this study shows that electricity outages are causing sales losses equivalent to \$82 billion a year. Firms are also incurring the costs of self-generated electricity, estimated to amount to $64 billion a year (including annualized capital expenditure). At almost \$300 billion a year, these figures highlight the substantial drag that unreliable infrastructure imposes on firms in developing countries. Yet, these figures are likely to be under-estimates as neither all countries nor all types of impacts are covered.
</div>


**Infrastructure Disruptions: How Instability Breeds Household Vulnerability** <br/> with Alvina Erman, Julie Rozenberg, Jun Rentschler, Paolo Avner and Stéphane Hallegatte <br/>

<div class="button-bar">
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3430512" class="button_that_looks_like_link">paper</a>
//
<button class="button_that_looks_like_link" role="button" onclick="hide_buttons('infrastructure_disruption')">abstract</button>
</div>

<div id="infrastructure_disruption" style="display: none;">
This review examines the literature on the welfare impacts of infrastructure disruptions. There is widespread evidence that households suffer from the consequences of a lack of infrastructure reliability, and that being connected to the grid is not sufficient to close the infrastructure gap. Disruptions and irregular service have adverse effects on household welfare, due to missed work and education opportunities, and negative impact on health. Calibrating costs of unreliable infrastructure on existing willingness to pay assessments, we estimate the welfare losses associated with blackouts and water outages. Overall, between 0.1 and 0.2 percent of GDP would be lost each year because of unreliable infrastructure -- electricity, water and transport.
</div>


<br/>

